### ISSUE TITLE
Non-square tiles produces latitudinal effects offset for GetMap osgrid

### ISSUE THREAD

**Issue by DuncanRowland** [nbnuk/nbnatlas-issues#175]
osgrid tiles seems to work OK when they are square (512x512)

https://records-ws.nbnatlas.org/ogc/wms/reflect?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A3857&BBOX=-626172.1357121639,7514065.628545966,0,8140237.764258131&WIDTH=512&HEIGHT=512&FORMAT=image/png&LAYERS=species:Martes+martes

https://records-ws.nbnatlas.org/ogc/wms/reflect?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A3857&BBOX=-626172.1357121639,7514065.628545966,0,8140237.764258131&WIDTH=512&HEIGHT=512&FORMAT=image/png&LAYERS=species:Martes+martes&ENV=colourmode:osgrid;color:ffff00;name:circle;size:4;opacity:0.5;gridlabels:true;gridres:singlegrid

BUG: Latitudinal offset linked to difference between Height and Width (e.g. 700x512)

https://records-ws.nbnatlas.org/ogc/wms/reflect?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A3857&BBOX=-626172.1357121639,7514065.628545966,0,8140237.764258131&WIDTH=700&HEIGHT=512&FORMAT=image/png&LAYERS=species:Martes+martes

https://records-ws.nbnatlas.org/ogc/wms/reflect?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A3857&BBOX=-626172.1357121639,7514065.628545966,0,8140237.764258131&WIDTH=700&HEIGHT=512&FORMAT=image/png&LAYERS=species:Martes+martes&ENV=colourmode:osgrid;color:ffff00;name:circle;size:4;opacity:0.5;gridlabels:true;gridres:singlegrid

**Comment by burkmarr** [comment]
This is a real problem in the QGIS environment. The dimensions of QGIS' map view window is not under the direct control of the user and often changes size and aspect ratio when tools are docked, undocked etc. The attached image shows a couple of maps generated from QGIS with the calls shown below. The 'dots' are not displaced but the grid squares are.

https://records-ws.nbnatlas.org/ogc/ows?q=family:Falconidae&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=-1861756.85242144158110023,6035214.72085938975214958,1268269.50042899837717414,8671269.36315673589706421&SRS=EPSG:3857&WIDTH=678&HEIGHT=571&LAYERS=species:Falco_peregrinus&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

https://records-ws.nbnatlas.org/ogc/ows?q=family:Falconidae&ENV=colourmode:osgrid;color:ffff00;name:circle;size:4;opacity:0.5;gridlabels:false;gridres:singlegrid&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=-1861756.85242144158110023,6035214.72085938975214958,1268269.50042899837717414,8671269.36315673589706421&SRS=EPSG:3857&WIDTH=678&HEIGHT=571&LAYERS=species:Falco_peregrinus&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

![nbn1](https://cloud.githubusercontent.com/assets/9275178/24189431/dc8641f0-0edc-11e7-83eb-641b47677e45.png)

**Comment by djtfmartin** [comment]
i think this is fixed in production. please reopen if not.

**Comment by burkmarr** [comment]
Hi @djtfmartin (cc @DuncanRowland). It's better than it was but I'm still seeing an offset. For example see the image below which was generated from the WMS call shown. If you would like me to do anything specific to test this or to illustrate the problem, please let me know. (I don't have the necessary privilege to re-open the issue - will you do it?)  

https://records-ws.nbnatlas.org/ogc/ows?q=genus:Streptopelia&ENV=name:circle;opacity:1.0;size:6;color:32f50f;colourmode:osgrid;gridres:singlegrid;gridlabels:true;&OUTLINE=TRUE&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=227912.15823735491721891,78800.16174101334763691,356094.56507760903332382,213472.81702887528808787&SRS=EPSG:27700&WIDTH=632&HEIGHT=664&LAYERS=species:Streptopelia_turtur&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

![offset](https://cloud.githubusercontent.com/assets/9275178/24561195/c13b5dc8-163d-11e7-849d-59ff240caa0f.png)

**Comment by djtfmartin** [comment]
Thanks @burkmarr 

A few more details of how to reproduce would be helpful. 
If you have chance, please email @DuncanRowland and me.

This is a screen shot of the a map rendered in 27700 projection with WMS from the Atlas serving grids for records at 10k and 1k with a base layer of 10km grids in grey (served from vanilla geoserver). As you can see its all aligning fine.

<img width="1118" alt="screenshot 2017-03-31 20 58 57" src="https://cloud.githubusercontent.com/assets/444897/24567336/2afd45a2-1655-11e7-8623-7e28e5d980a9.png">

**Comment by burkmarr** [comment]
My sincerest apologies @djtfmartin and @DuncanRowland - the mistake was mine. I won't bore you with the details, but I was offsetting my own grids (to help out some biologists in Luxembourg!). I hope that neither of you spent too much time investigating this spurious problem.

**Comment by djtfmartin** [comment]
no worries @burkmarr 
Thanks for letting us know and thanks for your help - much appreciated :)
