### ISSUE TITLE
Disabling or managing alerts

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#192]
I get these error messages when clicking the 'disable or manage my alerts' link within the Atlas alerts email (see screenshots) The datasets are now however relevant to the UK and not Australia as per an earlier reported issue

![error message](https://cloud.githubusercontent.com/assets/26628372/24507113/7c3d0032-1557-11e7-91c6-5c58021b8169.jpg)
![security warning](https://cloud.githubusercontent.com/assets/26628372/24507114/7c3e15ee-1557-11e7-8916-a92b004e65ea.jpg)

**Comment by djtfmartin** [comment]
Thanks @SarahHyslop can you forward the email to me ?

**Comment by djtfmartin** [comment]
I think this is fixed, but please reopen if not.

**Comment by SarahHyslop** [comment]
Hi Dave

 

Thanks for sorting this.  I have tried to click on the unsubscribe link within the original email I received and I still get the same error message but when I get a new email I will try this again.

 

Sarah

 

Sarah Hyslop

National Biodiversity Network Finance and Business Officer

T: 0115 924 7132

E:  <mailto:s.hyslop@nbn.org.uk> s.hyslop@nbn.org.uk  

 

Please note that my working days in the office are Monday, Tuesday, Thursday and working from home on a Friday  

 

National Biodiversity Network website: www.nbn.org.uk <http://www.nbn.org.uk/>   

NBN Atlas: www.nbnatlas.org <http://www.nbnatlas.org/> 

 

 

NBN Trust - Registered in England and Wales - Company no.3963387 - Registered charity no. 1082163.  

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney Street, Lace Market, Nottingham NG1 1LL

 

   

 <https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts>         <https://twitter.com/NBNTrust>  @NBNTrust        <https://twitter.com/nbnatlas>  @NBNAtlas        <https://www.linkedin.com/groups/National-Biodiversity-Network-148939/about>

**Comment by SarahHyslop** [comment]
Just tried to unsubscribe from the datasets alert email and get this message; 
![log out message](https://cloud.githubusercontent.com/assets/26628372/25236361/8f157b24-25df-11e7-9499-a22259613ee3.jpg)
