### ISSUE TITLE
Unable to download list of registered users

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#444]
I'm trying to download the registered users list to put an updated number into Network News, but I'm getting the error message below.  If this is a hard to resolve issue, can anyone else access an updated figure please?  I don't include those who haven't activated their account.  Sorry for short deadline, but Network News is due to go out today!
HTTP Status 403 -
type Status report
message
description Access to the specified resource has been forbidden.

**Comment by reupost** [comment]
Hi Mandy - can you send me a link to the page you were looking at?  I'm new to the Admin functionality but I'll try to help.

**Comment by sophiathirza** [comment]
I'm back online and will have a look as well. Sorry, it's public holidays here.

**Comment by MandyHenshall** [comment]
Thanks Reuben.  It's on "My profile" -> Admin tools->and then user administration.  I don't think the link will work as you need to be logged in, but just in case: https://auth.nbnatlas.org/userdetails/admin

**Comment by sophiathirza** [comment]
I have the same error, both on the website and through the API. @djtfmartin do you know what the problem could be? thanks.

**Comment by reupost** [comment]
Yes, me too.  I can look at this later this eve if its still a problem, but not right now - sorry.

**Comment by MandyHenshall** [comment]
Thanks both.  We (the office) seem to have an issue with emails at the moment, so I can't send Network News out now anyway! Will need to do so in the morning though, but it can go without that figure if needs be.

**Comment by reupost** [comment]
Mandy, I've emailed you a stop-gap list which is hopefully ok.  I'll be online again early in the morning if you need anything else.  Otherwise we'll need to dig a little deeper to find out what is causing the problem.

**Comment by djtfmartin** [comment]
assume this is now fixed

**Comment by reupost** [comment]
I'm still experiencing this issue.  I get a 403 error on the CSV download of the list of users, and an SSL certificate problem if I try the web service.  This could be because my IP address is not authorised to use the service.   

@MandyHenshall , could you give it a try please?

@sophiathirza - does it work for you?

**Comment by djtfmartin** [comment]
sorry @reupost, there was a separate email thread - should have cc-ed you.

Its IP restricted. I'll forward the email to you.

**Comment by GiselleSterry** [comment]
Hi @djtfmartin I have lost the ability to download reports. Just tried for the first time since moving office. Mandy just tried and cant do it either - both get 403 message
thanks

**Comment by djtfmartin** [comment]
thanks @GiselleSterry  - is this download usage reports or lists of users ?

**Comment by GiselleSterry** [comment]
Hi @djtfmartin its the list of users report. Not tried the usage reports yet.

**Comment by GiselleSterry** [comment]
Just tried and I am able to download a user report for a data provider. So its just the list of registered users I cant download. thanks

**Comment by GiselleSterry** [comment]
Hi @djtfmartin I have reopened this so doesn't get forgotten. Thanks

**Comment by reupost** [comment]
HI @GiselleSterry - could you send me your IP address (you can see it on e.g. https://www.whatismyip.com/)?  Then I can check to make sure you are whitelisted.

**Comment by GiselleSterry** [comment]
[redacted]

thanks @reupost

**Comment by reupost** [comment]
It looks like the system needs an IPv4 address (like xx.xx.xx.xx)  rather than an IPv6 address.  Would you mind seeing if http://test-ipv6.com/ shows you an IPv4 address for you?

**Comment by GiselleSterry** [comment]
[redacted] @reupost thanks

**Comment by reupost** [comment]
No problem - could you try now?  I think it should be fixed.

**Comment by GiselleSterry** [comment]
thanks - its worked.

**Comment by MandyHenshall** [comment]
Mine is [redacted] @reupost

**Comment by reupost** [comment]
Added :)

**Comment by MandyHenshall** [comment]
It worked for me too. Thank you @reupost !

**Comment by GiselleSterry** [comment]
Hi @reupost . 
This isnt working again for both @MandyHenshall and myself. Can you look at this again please. Many thanks!

**Comment by reupost** [comment]
Could you send me your IP addresses again please and I'll take a look?

**Comment by MandyHenshall** [comment]
@reupost If there is any chance you could pull me off the list or tell me the number of registered and active users please it would be much appreciated.  I am sending Network News out today and put the new figures in each month. Thank you  ;-)

IP address is the same for both of us: [redacted]

**Comment by reupost** [comment]
(Checked actual IPs from apache logs, which was different, and added that. Not sure why. Now working)

**Comment by GiselleSterry** [comment]
@reupost thanks - worked for me too.

**Comment by MandyHenshall** [comment]
@reupost I'm sorry to report that this has stopped working again.  Could you try and weave your magic again please?

**Comment by reupost** [comment]
@MandyHenshall - no problem.  Could you try again, and if you are still blocked, send me your IP address?  Thanks!

**Comment by MandyHenshall** [comment]
Thanks @reupost it's worked again now!
