### ISSUE TITLE
Caddisfly - explore records by taxonomy error

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#703]
For dataset - Caddisfly (Trichoptera) records from Britain to December 2018 - Under digitised records, when I click "Show information" rather than "show records" I get a HTTP Status 404 error, e.g.
![Caddisfly HTTP error](https://user-images.githubusercontent.com/27201815/54691890-fa79d780-4b1b-11e9-9198-fa230e2cf9d4.jpg)
 https://registry.nbnatlas.org/species/Insecta_(class)

**Comment by sophiathirza** [comment]
I've never clicked on that link before, it took me a while to find it.

![image](https://user-images.githubusercontent.com/1651015/54692271-08802600-4b25-11e9-8a99-a12eb75796c4.png)

**Comment by sophiathirza** [comment]
Should it link to the species page?

**Comment by MandyHenshall** [comment]
I'm not sure if you're asking me or Reuben, but I assume so.

**Comment by reupost** [comment]
Fixed

**Comment by sophiathirza** [comment]
I still get an error - though a different one:
![image](https://user-images.githubusercontent.com/1651015/54757505-a7228a80-4bea-11e9-9efd-d75038a34331.png)

**Comment by reupost** [comment]
Right, sorry, I didn't test this thoroughly at all. The link now points to the correct place (species.nbnatlas.org) but I see it only works for species, all higher-taxonomy links are broken. It looks like some changes need to be made to rewrite a link so that e.g. https://species.nbnatlas.org/species/Arge_(genus) rather points to https://species.nbnatlas.org/search?q=Arge&fq=rank:genus and https://species.nbnatlas.org/species/Insecta_(class) points to https://species.nbnatlas.org/search?q=Insecta&fq=rank:class

**Comment by sophiathirza** [comment]
Great, thanks.
